<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7LW5Klr\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7LW5Klr/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/Container7LW5Klr.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\Container7LW5Klr\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \Container7LW5Klr\App_KernelEnvDebugContainer([
    'container.build_hash' => '7LW5Klr',
    'container.build_id' => '028e250e',
    'container.build_time' => 1587972815,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7LW5Klr');
