<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAlcWRZX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAlcWRZX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAlcWRZX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAlcWRZX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAlcWRZX\App_KernelDevDebugContainer([
    'container.build_hash' => 'AlcWRZX',
    'container.build_id' => '7a52b6b7',
    'container.build_time' => 1600975118,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAlcWRZX');
